### ISSUE TITLE
Retrieve CABLE from GitHub repository instead of SVN

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#183]
We need this to be released on time for the CABLE transition to GitHub. Should we have both options available at first if we need to compare with something that hasn't been moved to GitHub?

- [x] #204
- [x] #199 
- [ ] #203

**Comment by SeanBryan51** [comment]
We will probably need to change the way we specify CABLE branches (realisations). I propose we replace the [`path` key](https://benchcab.readthedocs.io/en/v2.0.0/user_guide/config_options/#path) with a `repo` key which can be used to specify an SVN repository or a Git repository:
```yaml
realisations:
  - repo:
      svn: branches/Users/foo/my_branch
```
```yaml
realisations:
  - repo:
      git: 136-some-feature-branch
```
