### ISSUE TITLE
benchcab user feedback :)

### ISSUE THREAD

**Issue by bibivking** [CABLE-LSM/benchcab#184]
Hi Claire and Sean,

I used benchcab for CABLE-GW and CABLE trunk versions a few months ago and found two things were a bit annoying. CABLE-GW and the trunk version are expected different namelist files. I am wondering whether you could let benchcab read different namelist files for different CABLE versions, which will give more freedom to the model tests. Additionally, when I submitted the benchcab outputs and ran an analysis on modelevaluation.org, I could not figure out which simulation was which version of CABLE since there wasn't a specific version name given to modelevaluation.org. It might be good if we could let the user name their versions and show these names in modelevaluation.org. Many thanks!

**Comment by SeanBryan51** [comment]
Regarding the issue around specifying the namelist file for each branch, I guess the question is do we want to run namelist configurations that have a lot of differences compared to [the base namelist file](https://github.com/CABLE-LSM/bench_example/blob/main/namelists/cable.nml)? If yes, then using the [`patch`](https://benchcab.readthedocs.io/en/latest/user_guide/config_options/#+realisation.patch) and [`patch_remove`](https://benchcab.readthedocs.io/en/latest/user_guide/config_options/#+realisation.path_remove) to specify the namelist will be pain to configure and we are probably better off specifying the path to a namelist file. I guess this could come up if we want to test against a namelist configuration that was tuned for a specific model version?

For the modelevaluation.org issue, I guess we will have to bring that up with Gab? It would be great if we can dump issues relating to modelevaluation.org on somewhere like GitHub. @ccarouge @bschroeter can we put the analysis scripts we use inside a GitHub repo?

**Comment by ccarouge** [comment]
@SeanBryan51 For modelevaluation.org, there is already [a forum topic](https://forum.access-hive.org.au/t/analysis-plots-for-benchcab/878) we can use to collect the issues. Otherwise, we aren't working on the analysis scripts, this is done by Gab, John and Isaac, so it would be for them to decide where they want the issues.

**Comment by ccarouge** [comment]
@bibivking I am reticent to allow users to give their own namelist files. This is because the core focus for `benchcab` is to provide *standard* scientific evaluation for CABLE. By saying "standard", we want to ensure the namelist options used for one evaluation are the same as for another. This is to ensure the evaluations are comparable.

Obviously, `benchcab` is more flexible than that. We had to take into account various use cases (test with a new feature in one branch only, test with one branch based on an older version). This means branches can be run with different namelist options. But I think it is important to make it obvious what is different between the namelists used in the 2 branches. And I feel we would lose that by allowing to give the namelists directly.

We discussed this a bit with @SeanBryan51 and @bschroeter and **here are our ideas:**

- use a simpler syntax for `patch`. Remove the `{` and simply use `-` in front of options.
- or give the patch via a namelist "subset" file. Instead of giving a full namelist file, we could have a subset namelist file that only contains the options that are different for that branch. This might be the easiest for users as it's the same format as the CABLE namelist file.


**For the plots,** I totally agree. Especially, the legend talks about "integration branch" which is not used anymore (it was in the original design by Martin). We will pass on to Gab and co.
But **would that help if the filenames included the branch name as well instead of only `_R#`?**

**Comment by SeanBryan51** [comment]
It could be possible to enforce standardisation in the work directory used to run benchcab, i.e. a [bench_example](https://github.com/CABLE-LSM/bench_example) specifically for running the standard set of tests. The appropriate namelist configurations to use in the standard tests could be committed to Git. Could this get the best of both worlds if users want to use their own configurations by creating a modified [bench_example](https://github.com/CABLE-LSM/bench_example)?

**Comment by ccarouge** [comment]
@SeanBryan51 this does not work for a new feature. Contributions to CABLE for a new feature need to run benchcab with a patch on one of the branch. But that patch must be restricted to the new feature options only.

**Comment by SeanBryan51** [comment]
I agree it would take some reworking of how we configure the ensemble of tasks in [bench_example/config.yaml](https://github.com/CABLE-LSM/bench_example/blob/main/config.yaml). 

I think if I had to start over, I would like to do something like this in config.yaml:
```yaml
realisations:
  - name: trunk
    path: trunk
  - name: bar
    path: branches/Users/foo/bar

fluxsite:
  tasks:
    matrix:
      namelists: [S0.nml, S1.nml, ...]
      forcings: [AU-Tum, AU-How, ...]
      realisations:
        - trunk
        - bar:
            patch:
              cable:
                my_feature: True
    # Or if we just want to force each realisation to use a specific namelist file
    matrix:
      forcings: [AU-Tum, AU-How, ...]
      realisations:
        - trunk:
          namelist: S0.nml
        - bar:
          namelist: my_bespoke_namelist.nml
  # Or if we do not want to specify a matrix:
  tasks:
    - task_name: task_a
      namelist: S0.nml
      forcing: AU-Tum
      realisation: trunk
    - task_name: task_b
      namelist: my_bespoke_namelist.nml
      forcing: AU-Tum
      realisation: bar
```
