### ISSUE TITLE
Not sure storage flags are being honoured

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/benchcab#188]
Hey @SeanBryan51,

In trying to run integration tests for #143, with a pre-canned configuration file it does not appear that the flux site storage flags are actually being set.

https://github.com/CABLE-LSM/benchcab/blob/0b36493f81fbd75c89829c8dc4d65ac6d7968609/benchcab/utils/pbs.py#L32-L35

My config file (rendered at runtime):

```yaml
project: rp23

experiment: AU-Tum

realisations:
  - path: trunk
  - path: branches/Users/sb8430/test-branch

modules: [
  intel-compiler/2021.1.1,
  netcdf/4.7.4,
  openmpi/4.1.0
]

fluxsite:
    pbs:
        storage:
            - scratch/rp23
```

What eventuates is a job trying to run without knowledge of the rp23 scratch mount point - meaning that integration tests on my local dev installation of benchcab on rp23 simply fail with a file not found.

Am I doing something wrong, or is there an issue with passing the user-supplied flux site pbs directives through to the job script renderer?
